=== AMWA-TV/maj/src/main/java/tv/amwa/maj/extensions/example/metadict.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright 2016 Advanced Media Workflow Assocation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

	 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"
	 	targetNamespace="http://www.smpte-ra.org/schemas/2001-1/2007/metadict"
	 	xmlns:tns="http://www.smpte-ra.org/schemas/2001-1/2007/metadict">
	<xs:element name="Baseline" type="tns:mBaselineType"/>
	<xs:element name="Extension" type="tns:mBaselineType"/>
	<xs:complexType name="mBaselineType">
		<xs:all>
			<xs:element name="Identification" type="tns:mAUID"/>
			<xs:element name="Symbolspace" type="xs:anyURI"/>
			<xs:element name="PreferredPrefix" type="xs:NCName" minOccurs="0"/>
			<xs:element name="Description" type="xs:string" minOccurs="0"/>
			<xs:element name="Definitions">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element name="ClassDefinition">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ParentClass" type="tns:mMetaDefRef" minOccurs="0"/>
									<xs:element name="IsConcrete" type="xs:boolean"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="PropertyDefinition">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="Type" type="tns:mMetaDefRef"/>
									<xs:element name="IsOptional" type="xs:boolean"/>
									<xs:element name="IsUniqueIdentifier" type="xs:boolean" minOccurs="0"/>
									<xs:element name="LocalIdentification" type="tns:mLocalIdentificationType"/>
									<xs:element name="MemberOf" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionCharacter">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionEnumeration">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ElementType" type="tns:mMetaDefRef"/>
									<xs:element name="Elements">
										<xs:complexType>
											<xs:sequence minOccurs="0" maxOccurs="unbounded">
												<xs:element name="Name" type="xs:token"/>
												<xs:element name="Value" type="xs:long"/>
												<xs:element name="Description" type="xs:string" minOccurs="0"/>
											</xs:sequence>
										</xs:complexType>
										<xs:unique name="mTypeDefEnumNamesUnique">
											<xs:selector xpath="Name"/>
											<xs:field xpath="."/>
										</xs:unique>
										<xs:unique name="mTypeDefEnumValuesUnique">
											<xs:selector xpath="Value"/>
											<xs:field xpath="."/>
										</xs:unique>
									</xs:element>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionExtendibleEnumeration">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="ExtendibleEnumerationElement">
							<xs:complexType>
								<xs:all>
									<xs:element name="ElementOf" type="tns:mMetaDefRef"/>
									<xs:element name="Name" type="xs:token"/>
									<xs:element name="Value" type="tns:mAUID"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionFixedArray">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ElementType" type="tns:mMetaDefRef"/>
									<xs:element name="ElementCount" type="xs:unsignedInt"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionIndirect">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionInteger">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="Size">
										<xs:simpleType>
											<xs:restriction base="xs:unsignedByte">
												<xs:enumeration value="1"/>
												<xs:enumeration value="2"/>
												<xs:enumeration value="4"/>
												<xs:enumeration value="8"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="IsSigned" type="xs:boolean"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionOpaque">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionRecord">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="Members">
										<xs:complexType>
											<xs:sequence minOccurs="0" maxOccurs="unbounded">
												<xs:element name="Name" type="xs:NCName"/>
												<xs:element name="Type" type="tns:mMetaDefRef"/>
											</xs:sequence>
										</xs:complexType>
										<xs:unique name="mTypeDefRecordMemberNamesUnique">
											<xs:selector xpath="Name"/>
											<xs:field xpath="."/>
										</xs:unique>
									</xs:element>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionRename">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="RenamedType" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionSet">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ElementType" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionStream">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionString">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ElementType" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionStrongObjectReference">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ReferencedType" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionVariableArray">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ElementType" type="tns:mMetaDefRef"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element name="TypeDefinitionWeakObjectReference">
							<xs:complexType>
								<xs:all>
									<xs:element name="Identification" type="tns:mAUID"/>
									<xs:element name="Symbol" type="xs:NCName"/>
									<xs:element name="Description" type="xs:string" minOccurs="0"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="ReferencedType" type="tns:mMetaDefRef"/>
									<xs:element name="TargetSet" type="tns:mMetaDefRefArray"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
				<xs:unique name="mDefSymbolsUnique">
					<xs:selector xpath="*"/>
					<xs:field xpath="Symbol"/>
				</xs:unique>
				<xs:unique name="mDefIdentificationUnique">
					<xs:selector xpath="*"/>
					<xs:field xpath="Identification"/>
				</xs:unique>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:simpleType name="mAUID">
		<xs:restriction base="xs:anyURI">
			<xs:pattern value="urn:smpte:ul:[0-9a-fA-F]{8}\.([0-9a-fA-F]){8}\.([0-9a-fA-F]){8}\.([0-9a-fA-F]){8}"/>
			<xs:pattern value="urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="mMetaDefRef">
		<xs:union memberTypes="tns:mAUID xs:NCName">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[^ ]+ \i\c*"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:complexType name="mMetaDefRefArray">
		<xs:sequence>
			<xs:element name="MetaDefRef" type="tns:mMetaDefRef" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="mLocalIdentificationType">
        <xs:union memberTypes="xs:unsignedShort">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="0x[0-9a-fA-F]{1,4}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
	</xs:simpleType>
</xs:schema>

=== AMWA-TV/maj/src/main/java/tv/amwa/maj/extensions/example/SimpleExtension.xml
<?xml version="1.0" encoding="UTF-8"?>

<Extension xmlns="http://www.smpte-ra.org/schemas/2001-1/2007/metadict"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.smpte-ra.org/schemas/2001-1/2007/metadict metadict.xsd">
	
	<Identification>urn:smpte:ul:060e2b34.01040101.0f201101.00000000</Identification>
	<Symbolspace>http://amwa.tv/maj/extensions/example</Symbolspace>
	<PreferredPrefix>eg</PreferredPrefix>
	<Description>A simple example of how to write an extension metadata set.</Description>
	
	<Definitions>
	
		<!-- SimpleDescription -->
		<ClassDefinition>
			<Symbol>SimpleDescription</Symbol>
			<Name>SimpleDescription</Name>
			<Identification>urn:smpte:ul:060e2b34.02530101.0f201101.01010000</Identification>
			<Description>Very basic description of an item, based on a few Dublin Core terms.</Description>
			<ParentClass>DescriptiveFramework</ParentClass>
			<IsConcrete>true</IsConcrete>
		</ClassDefinition>
		<PropertyDefinition>
			<Symbol>Title</Symbol>
			<Name>Title</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01010100</Identification>
			<Description>A name given to the resource.</Description>
			<MemberOf>SimpleDescription</MemberOf>
			<Type>UTF16String</Type>
			<IsOptional>false</IsOptional>
			<LocalIdentification>0</LocalIdentification> <!-- 0 = generate dynamic -->
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>DateAccepted</Symbol>
			<Name>DateAccepted</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01010200</Identification>
			<Description>Date of acceptance of the resource.</Description>
			<MemberOf>SimpleDescription</MemberOf>
			<Type>DateStruct</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>Identifier</Symbol>
			<Name>Identifier</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01010300</Identification>
			<Description>An unambiguous reference to the resource within a given context.</Description>
			<MemberOf>SimpleDescription</MemberOf>
			<Type>UTF16String</Type>
			<IsOptional>false</IsOptional>
			<LocalIdentification>0</LocalIdentification>
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>Type</Symbol>
			<Name>Type</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01010400</Identification>
			<Description>Identity of the genre of the resource.</Description>
			<MemberOf>SimpleDescription</MemberOf>
			<Type>DCMIType</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>Creator</Symbol>
			<Name>Creator</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01010500</Identification>
			<Description>An entity primarily responsible for making the resource.</Description>
			<MemberOf>SimpleDescription</MemberOf>
			<Type>ContributorStrongReference</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>
		</PropertyDefinition>

		<!--  Contributor -->
		<ClassDefinition>
			<Symbol>Contributor</Symbol>
			<Name>Contributor</Name>
			<Identification>urn:smpte:ul:060e2b34.02530101.0f201101.01020000</Identification>
			<Description>Entity that creates or contributes to a resource.</Description>
			<ParentClass>DescriptiveObject</ParentClass>
			<IsConcrete>false</IsConcrete>
		</ClassDefinition>
		<PropertyDefinition>
			<Symbol>Name</Symbol>
			<Name>Name</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01020100</Identification>
			<Description>Name of the contributor.</Description>
			<MemberOf>Contributor</MemberOf>
			<Type>UTF16String</Type>
			<IsOptional>false</IsOptional>
			<LocalIdentification>0</LocalIdentification>		
		</PropertyDefinition>

		<!-- Person -->
		<ClassDefinition>
			<Symbol>Person</Symbol>
			<Name>Person</Name>
			<Identification>urn:smpte:ul:060e2b34.02530101.0f201101.01030000</Identification>
			<Description>Person who makes and/or contributes a resource.</Description>
			<ParentClass>Contributor</ParentClass>
			<IsConcrete>true</IsConcrete>
		</ClassDefinition>
		<PropertyDefinition>
			<Symbol>Email</Symbol>
			<Name>Email</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01030100</Identification>
			<Description>Contact e-mail address for the person.</Description>
			<MemberOf>Person</MemberOf>
			<Type>UTF16String</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>		
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>DOB</Symbol>
			<Name>DOB</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01030200</Identification>
			<Description>Date of birth of the person.</Description>
			<MemberOf>Person</MemberOf>
			<Type>DateStruct</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>		
		</PropertyDefinition>
		
		<!-- Organisation -->
		<ClassDefinition>
			<Symbol>Organisation</Symbol>
			<Name>Organisation</Name>
			<Identification>urn:smpte:ul:060e2b34.02530101.0f201101.01040000</Identification>
			<Description>Organisation that makes or contributes a resource.</Description>
			<ParentClass>Contributor</ParentClass>
			<IsConcrete>true</IsConcrete>
		</ClassDefinition>
		<PropertyDefinition>
			<Symbol>CompanyNo</Symbol>
			<Name>CompanyNo</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01040100</Identification>
			<Description>Registered company number for the organisation.</Description>
			<MemberOf>Organisation</MemberOf>
			<Type>UInt64</Type>
			<IsOptional>false</IsOptional>
			<LocalIdentification>0</LocalIdentification>		
		</PropertyDefinition>
		<PropertyDefinition>
			<Symbol>Contact</Symbol>
			<Name>Contact</Name>
			<Identification>urn:smpte:ul:060e2b34.01010101.0f201101.01040200</Identification>
			<Description>Contact person at the organisation responsible for the contributed resource.</Description>
			<MemberOf>Organisation</MemberOf>
			<Type>PersonStrongReference</Type>
			<IsOptional>true</IsOptional>
			<LocalIdentification>0</LocalIdentification>		
		</PropertyDefinition>
		
		<!-- Type definitions -->
		<TypeDefinitionEnumeration>
			<Symbol>DCMIType</Symbol>
			<Name>DCMIType</Name>
			<Identification>urn:smpte:ul:060e2b34.01040101.0f201101.01000000</Identification>
			<Description>Different genres of resource.</Description>
			<ElementType>UInt8</ElementType>
			<Elements> 
				<Name>MovingImage</Name>
				<Value>1</Value>
				<Name>StillImage</Name>
				<Value>2</Value>
				<Name>Sound</Name>
				<Value>3</Value>
				<Name>DataSet</Name>
				<Value>4</Value>
			</Elements>
		</TypeDefinitionEnumeration>
		
		<TypeDefinitionStrongObjectReference>
			<Symbol>ContributorStrongReference</Symbol>
			<Name>ContributorStrongReference</Name>
			<Identification>urn:smpte:ul:060e2b34.01040101.0f201101.02000000</Identification>
			<Description>Strong reference to the value of a contributor.</Description>
			<ReferencedType>Contributor</ReferencedType>
		</TypeDefinitionStrongObjectReference>
		
		<TypeDefinitionStrongObjectReference>
			<Symbol>PersonStrongReference</Symbol>
			<Name>PersonStrongReference</Name>
			<Identification>urn:smpte:ul:060e2b34.01040101.0f201101.03000000</Identification>
			<Description>Strong reference to the value of a person used as a contact.</Description>
			<ReferencedType>Person</ReferencedType>
		</TypeDefinitionStrongObjectReference>
	</Definitions>
	
</Extension>
